### ISSUE TITLE
バイナリのサイズが 1MB を超えている

### ISSUE THREAD

**Issue by atom9393** [ponpoko094/MHX3gx#24]
コメントを書く前にまちがえて Enter 押してしまいました。

デフォルトの 3gxtool ではビルドできないので、書いておくと良いと思います。

**Comment by HIDE810** [comment]
It is written in `README.md` but the tool recommended by @ponpoko094 is only for Windows users.  
I'm going to publish another one for Linux soon, so If you are a Linux user, you can use it.

**Comment by HIDE810** [comment]
OK, I made its link.

Download URL:
https://cdn.discordapp.com/attachments/479233444249862174/908696881297760296/3gxtool

For Linux users, I would appreciate it if you add this link to `README.md`. @ponpoko094

**Comment by atom9393** [comment]
了解

**Comment by ponpoko094** [comment]
I added the link to `README.md`. @HIDE810

**Comment by HIDE810** [comment]
> I added the link to `README.md`. @HIDE810

Thanks!
